openapi: 3.0.0
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Get all tasks
      description: Retrieve a list of all tasks
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        500:
          description: Server error
    post:
      tags:
        - Tasks
      summary: Create a new task
      description: Create a new task by providing task details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        201:
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Bad request. Validation error.
        500:
          description: Server error
  /tasks/{id}:
    put:
      tags:
        - Tasks
      summary: Update an existing task
      description: Update a task by providing the task ID and new data
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        200:
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Bad request. Validation error.
        404:
          description: Task not found
        500:
          description: Server error
    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: Delete a task by providing the task ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the task to delete
      responses:
        204:
          description: Task deleted successfully
        404:
          description: Task not found
        500:
          description: Server error

components:
  schemas:
    Task:
      type: object
      required:
        - title
        - description
        - completed
      properties:
        _id:
          type: string
          description: The auto-generated id of the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        completed:
          type: boolean
          description: Indicates whether the task is completed
        createdAt:
          type: string
          format: date-time
          description: The date the task was created
        updatedAt:
          type: string
          format: date-time
          description: The date the task was last updated
    TaskInput:
      type: object
      required:
        - title
        - description
        - completed
      properties:
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        completed:
          type: boolean
          description: Indicates whether the task is completed
