version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-manager
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - '27017:27017'
